Create Web Files
PukieDiederik/webserv pull request #11
Opened 2023-05-30 16:08 UTC by edgareu1

A first draft of the web files.

Created multiple pages (*.html), a stylesheet (index.css) and a script (index.js).

Pages were created for:
1. Content display (index.html);
2. Error display (error-pages/*.html);
3. Test redirects (redirects/*.html);
4. Test post/delete requests (form*.html).

A cgi folder was added (cgi-bin) to host our cgi scripts. Empty for now.

While the server is not working, `http-server` is a great tool to test this pages visually (does not work for CGI testing).

2023-05-31 15:03 UTC, PukieDiederik requested changes
Good start but i'd like to see the following changes:
- Delete/Justify redirect pages
- Make href use relative file paths instead of absolute. This is because if you have this website on `[authority]/test` for example `/index.js` looks for `[authority]/index.js` instead of `[authority]/test/index.js`

2023-06-08 16:32 UTC, edgareu1 commented on var/www/files/.keep
To save the uploaded files

2023-06-08 16:53 UTC, edgareu1 commented on var/www/index.html
> +							<a href="/redirects/permanent">
Just removed it the `var/www/redirect` folder

2023-06-08 17:18 UTC, edgareu1 commented on var/www/error-pages/403.html
> +		<link rel="stylesheet" href="/index.css">
Done

2023-06-08 17:18 UTC, edgareu1 commented on var/www/index.html
> +							<a href="/form">
Done

2023-06-09 00:25 UTC, PukieDiederik approved these changes
Everything looks good to me, really good job! For the next steps I recommend either creating a config file (though this might be better to wait after the parsing is implemented), or implementing the CGI files.

2023-06-09 00:26 UTC, merged