Implemented redirections
PukieDiederik/webserv pull request #60
Opened 2023-08-28 21:35 UTC by gde-alme

Might not be the best approach although it seems to work fine

2023-08-28 21:36 UTC, gde-alme commented
This PR has the commits from "Issue#52 PR"

2023-09-03 21:41 UTC, PukieDiederik requested changes
This seems like a weird way to handle redirections. Should it not just be handled by `src/Server.cpp:59-60`?

2023-09-03 21:41 UTC, PukieDiederik commented on include/HttpRequest.hpp
> +    void    set_target( const std::string& target );
This function is not necessary, the target can be set by calling `target() = "new/target"`.

2023-09-03 21:41 UTC, PukieDiederik commented on src/Server.cpp
> +HttpResponse    Server::handleRequest( HttpRequest& req)
The request is NEVER allowed to be changed by the server

2023-09-03 21:41 UTC, PukieDiederik commented on src/Server.cpp
> +        res = Server::handleRequest( req );
Why do we set the target and run handleRequest again? Why do we not just have the last 2 lines? The target redirect might not be for this server.

2023-09-05 19:03 UTC, edgareu1 submitted a review, later dismissed

2023-09-06 11:07 UTC, edgareu1 approved these changes

2023-09-06 13:28 UTC, merged