Efreire create cgi
PukieDiederik/webserv pull request #66
Opened 2023-09-02 19:35 UTC by edgareu1

2023-09-03 03:15 UTC, gde-alme approved these changes

2023-09-03 22:02 UTC, PukieDiederik requested changes
I think instead of only checking for a post request (like for example we also have the redirect file which would be more logical to be called with the GET method) we should check if cgi is enabled and if the file requested is a cgi script (based on the extension).

2023-09-04 13:30 UTC, edgareu1 commented on src/Server.cpp
> +                i++;
Done!

2023-09-10 12:42 UTC, gde-alme approved these changes

2023-09-25 15:53 UTC, PukieDiederik approved these changes
We discussed it together in person, looks good

2023-09-25 15:54 UTC, merged